import{S as f,i as u,a as g}from"./assets/vendor-951421c8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();const h=document.querySelector(".search-form"),b=document.querySelector(".search-input"),p=document.querySelector(".gallery-list"),a=document.querySelector(".loader"),n=document.querySelector(".load-more"),L=new f(".gallery a");let l=1,y="";h.addEventListener("submit",async i=>{i.preventDefault();const r=b.value.trim();if(r===""){u.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}y=r,l=1,a.style.display="block",p.innerHTML="",n.style.display="none",await m(y,l)});n.addEventListener("click",async()=>{l++,a.style.display="block",await m(y,l)});async function m(i,r){const e=`https://pixabay.com/api/?key=36996517-56800863ae540be6945d0f4f2&q=${i}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${15}`;try{const s=(await g.get(e)).data;if(s.hits.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3});return}p.innerHTML+=s.hits.map(o=>`<li class="gallery-item">
                <a href="${o.largeImageURL}" data-lightbox="gallery" data-title="${o.tags}">
                    <img class="img-item" src="${o.webformatURL}" alt="${o.tags}">
                </a>
                <ul class="image-properties">
                    <li>Likes <br/>${o.likes}</li>
                    <li>Views <br/>${o.views}</li>
                    <li>Comments <br/>${o.comments}</li>
                    <li>Downloads <br/>${o.downloads}</li>
                </ul>
            </li>`).join(""),a.style.display="none",L.refresh(),s.totalHits>r*15?n.style.display="block":n.style.display="none"}catch{u.error({message:"There has been a problem with your fetch operation!",position:"topRight",timeout:3e3}),a.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
