import{S as f,i as n,a as b}from"./assets/vendor-951421c8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&u(s)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function u(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();const L=document.querySelector(".search-form"),p=document.querySelector(".search-input"),m=document.querySelector(".gallery-list"),l=document.querySelector(".loader"),a=document.querySelector(".load-more"),w=new f(".gallery a");let c=1,y="";L.addEventListener("submit",async i=>{i.preventDefault();const r=p.value.trim();if(r===""){n.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}l.style.display="block",a.style.display="none",y=r,c=1,m.innerHTML="",await h(y,c)});a.addEventListener("click",async()=>{c+=1,l.style.display="block",await h(y,c),$()});async function h(i,r){const e=`https://pixabay.com/api/?key=36996517-56800863ae540be6945d0f4f2&q=${i}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${15}`;try{const s=(await b.get(e)).data;if(p.value="",s.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),l.style.display="none";return}const g=s.hits.map(o=>`<li class="gallery-item">
                <a href="${o.largeImageURL}" data-lightbox="gallery" data-title="${o.tags}">
                    <img class="img-item" src="${o.webformatURL}" alt="${o.tags}">
                </a>
                <ul class="image-properties">
                    <li>Likes <br/>${o.likes}</li>
                    <li>Views <br/>${o.views}</li>
                    <li>Comments <br/>${o.comments}</li>
                    <li>Downloads <br/>${o.downloads}</li>
                </ul>
            </li>`).join("");m.insertAdjacentHTML("beforeend",g),l.style.display="none",w.refresh(),s.totalHits<=r*15?(a.style.display="none",n.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):a.style.display="block"}catch{n.error({message:"There has been a problem with your fetch operation!",position:"topRight",timeout:3e3}),l.style.display="none"}}function $(){const i=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
