import{S as g,i as u,a as h}from"./assets/vendor-951421c8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();const b=document.querySelector(".search-form"),p=document.querySelector(".search-input"),m=document.querySelector(".gallery-list"),i=document.querySelector(".loader"),n=document.querySelector(".load-more"),L=new g(".gallery a");let l=1,y="";b.addEventListener("submit",async a=>{a.preventDefault();const r=p.value.trim();if(r===""){u.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}i.style.display="block",n.style.display="none",y=r,l=1,m.innerHTML="",await f(y,l)});n.addEventListener("click",async()=>{l+=1,i.style.display="block",await f(y,l)});async function f(a,r){const e=`https://pixabay.com/api/?key=36996517-56800863ae540be6945d0f4f2&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${15}`;try{const s=(await h.get(e)).data;if(p.value="",s.hits.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),i.style.display="none";return}setTimeout(()=>{m.innerHTML+=s.hits.map(o=>`<li class="gallery-item">
                <a href="${o.largeImageURL}" data-lightbox="gallery" data-title="${o.tags}">
                    <img class="img-item" src="${o.webformatURL}" alt="${o.tags}">
                </a>
                <ul class="image-properties">
                    <li>Likes <br/>${o.likes}</li>
                    <li>Views <br/>${o.views}</li>
                    <li>Comments <br/>${o.comments}</li>
                    <li>Downloads <br/>${o.downloads}</li>
                </ul>
            </li>`).join(""),i.style.display="none",L.refresh(),s.totalHits>r*15?n.style.display="block":n.style.display="none"},1e3)}catch{u.error({message:"There has been a problem with your fetch operation!",position:"topRight",timeout:3e3}),i.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
